name: Build Godot Project

on:
  workflow_call:
    inputs:
      COPY_BRIDGE:
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kronbergerspiele/ks-godot-ci:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: true

      - name: Setup Templates
        if: ${{ !env.ACT }}
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          rm -rf ~/.local/share/godot/templates/*
          mv /root/.local/share/godot/templates/* ~/.local/share/godot/templates/

      - name: Copy Bridge
        if: ${{ inputs.COPY_BRIDGE }}
        run: |
          rm -f docs/bridge.js
          cp jsgdbridge/index.js  docs/bridge.js

      - name: Build and Export
        run: |
          mkdir -p docs
          godot --export "ci" docs/game.html > build.log
          cat build.log
          grep -qv "Failed to build project" build.log
          ls -lah docs

      - name: Upload build
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v1
        with:
          name: docs
          path: docs
